#pragma once

#define STURDDLE_VERSION_MAJOR 2
#define STURDDLE_VERSION_MINOR 5
#define STURDDLE_VERSION_PATCH "1-rc10"

#define _STURDDLE_STR(x) #x
#define _STURDDLE_XSTR(x) _STURDDLE_STR(x)
#define STURDDLE_VERSION \
    _STURDDLE_XSTR(STURDDLE_VERSION_MAJOR) "." \
    _STURDDLE_XSTR(STURDDLE_VERSION_MINOR) "." \
    STURDDLE_VERSION_PATCH
