#!/usr/bin/env python3
"""
Build a per-bucket label-scale profile (JSON) from label_check report(s).

Parses the per-file bucket tables, aggregates |label| and |engine| sums
weighted by sample count, and emits ratio = sum|label| / sum|engine| per
bucket. Buckets with fewer than --min-n samples fall back to ratio 1.0.
The output feeds train.py --profile.

Usage:
    ./mkprofile.py report.txt [more_reports...] --match leela T80 --out profile.json
    ./mkprofile.py report.txt --files group.txt --out group.h5.profile.json
"""

import argparse
import json
import os
import re
import sys

BUCKETS = 16
ROW_RGX = re.compile(
    r"^\s+(\d+)\s+\S+\s+(?:QQ|QK|KQ|KK)\s+(\d+)\s+"
    r"[-+.\dnan]+\s+[-+.\dnan]+\s+[-+.\dnan]+\s+(\d+)\s+(\d+)\s+[.\dnan]+\s*$"
)


def main(args):
    label = [0.0] * BUCKETS
    engine = [0.0] * BUCKETS
    counts = [0] * BUCKETS
    files = []
    current = None

    wanted = None
    if args.files:
        wanted = {line.strip() for f in args.files for line in open(f) if line.strip()}

    for rp in args.reports:
        for line in open(rp):
            if line[:1] not in ("", " ", "\t", "\n") and line.rstrip().endswith(".h5"):
                current = line.strip()
                if wanted is not None:
                    if current in wanted:
                        files.append(current)
                elif not args.match or any(m in current for m in args.match):
                    files.append(current)
                continue
            if current not in files:
                continue
            m = ROW_RGX.match(line)
            if not m:
                continue
            b, n, ml, me = int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
            label[b] += n * ml
            engine[b] += n * me
            counts[b] += n

    if not files:
        sys.exit("no report files matched")
    print(f"using {len(files)} report file(s)", file=sys.stderr)

    overall = sum(label) / sum(engine) if sum(engine) else 1.0
    ratios = []
    for b in range(BUCKETS):
        if counts[b] < args.min_n or engine[b] == 0:
            print(f"bucket {b}: n={counts[b]}, falling back to overall ratio {overall:.3f}", file=sys.stderr)
            ratios.append(round(overall, 3))
        else:
            ratios.append(round(label[b] / engine[b], 3))

    profile = {
        "comment": f"generated by mkprofile.py from {', '.join(args.reports)}",
        "files": len(files),
        "positions": counts,
        "ratios": ratios,
    }
    text = json.dumps(profile, indent=2)
    if args.out and os.path.exists(args.out) and not args.force:
        sys.exit(f"{args.out}: exists, use --force to overwrite")
    if args.out:
        with open(args.out, "w") as f:
            f.write(text + "\n")
        print(f"wrote {args.out}")
    print(text if not args.out else "ratios: " + " ".join(f"{r:.3f}" for r in ratios))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("reports", nargs="+", help="label_check report file(s)")
    parser.add_argument("--match", nargs="*", help="only use report files whose path contains any of these substrings")
    parser.add_argument("--files", nargs="*", help="only use report files exactly listed in these text file(s)")
    parser.add_argument("--min-n", type=int, default=50, help="buckets with fewer samples default to ratio 1.0")
    parser.add_argument("--out", help="write profile JSON here (default: print to stdout)")
    parser.add_argument("--force", action="store_true", help="overwrite existing --out file")
    args = parser.parse_args()

    main(args)
